### PR TITLE
Adjust DocProperties ids after building the complete document

### PR DESCRIPTION
**Pull request by kimsey0**
Adjust DocProperties ids after building the complete document with headers and footers, instead of after appending each source.

Fixes OfficeDev/Open-Xml-PowerTools#91

### CODE REVIEW

**Comment by kimsey0** [comment]
I am closing and re-opening this PR to bump the CLA bot.

**Comment by kimsey0** [comment]
@EricWhiteDev: Any chance this could be merged?

**Comment by kimsey0** [comment]
@tomjebo, @EricWhiteDev: Could we have this merged, please?

**Comment by kimsey0** [comment]
I have added a test case that shows the bug and prevents any regressions.

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev Could you please look into this.

**Comment by kimsey0** [comment]
Thank you @EricWhiteDev and @ThomasBarnekow.

**Pull request merged**
