### PR TITLE
Ability to process Flat to OPC and OPC to Flat in memory.

### PR DESCRIPTION
**Pull request by lpperras**
Added a couple of overloads to make it possible to transfer a flat opc structure to a docx package and vice versa without writing to disk.

### CODE REVIEW

**Comment by EricWhiteDev** [comment]
@lpperras Hi, thank you!

I am in the final stages of putting together a cool new module for Open-Xml-PowerTools - watch for this near the beginning of next week.  :-)

Following that, I will be attending to some other Open-Xml-PowerTools issues, and will be looking at this and other PRs in detail.  If OK, please be patient - I will attend to this as soon as I release this new module.

Cheers, Eric

**Comment by ThomasBarnekow** [comment]
@lpperras and @EricWhiteDev The functionality to convert between OPC and Flat OPC in memory exists in the Open XML SDK. I had a PR for that and @EricWhiteDev merged that PR at the time.

**Comment by rashlab** [comment]
hi, what is the status of this functionality? thanks, Ran

**Comment by ThomasBarnekow** [comment]
@lpperras and @rashlab Are you still interested in this PR? If so, have you checked out the functionality that is already included in the Open XML SDK? What would this PR add to that?

**Comment by lpperras** [comment]
@ThomasBarnekow Could you please just point to the method that would do that in the Open XML SDK? I am fine with using this one instead. I had other fixes though in that PR, I'll create a separate branch for them and create another PR.

**Comment by ThomasBarnekow** [comment]
@lpperras Just call `ToFlatOpcString()` or `ToFlatOpcDocument()` on an instance of `OpenXmlPackage`. For example, if `wordDocument` is a `WordprocessingDocument`, `document.ToFlatOpcString()` produces a Flat OPC document `string`, whereas `document.ToFlatOpcDocument()` produces an `XDocument`.

**Comment by lpperras** [comment]
@ThomasBarnekow and how can I start from a flat to WordprocessingDocument?

**Comment by ThomasBarnekow** [comment]
@lpperras Try `WordprocessingDocument.FromFlatOpcString(string)` or `WordprocessingDocument.FromFlatOpcDocument(XDocument)`, for example.

**Pull request closed without merging**
