### PR TITLE
Allow xPath functions in footer rows and refactor

### PR DESCRIPTION
**Pull request by BrettBailey**
Allows expressions such as <Content Select="sum(./Orders//Quantity/text())"/> in the footer rows of tables. Plus Refactored  the evaluation of xpath to a new method

### CODE REVIEW

**Comment by chrlutz** [comment]
maybe my requirements addressed in pull-request 36 (see https://github.com/chrlutz/Open-Xml-PowerTools/commit/23fe566ad293e24dd6ca621bf1ce5cf4a3c076ef) are also solved here. It would be fine if you could test your solution again the test case described in https://github.com/chrlutz/Open-Xml-PowerTools/commit/c13d12256a15af42e93c6600261d9dbfc7c3e31d

**Comment by BrettBailey** [comment]
@chrlutz It looks to me as though my changes will address your issue.  I will try out the tests next time I'n in the code. Although do feel free to grab my branch and run those tests yourself :-)

**Comment by BrettBailey** [comment]
@EricWhiteDev Are you back from your travels yet :-) can this be pulled in?

**Comment by EricWhiteDev** [comment]
@BrettBailey Yes, I'm back.  I can address those next week.  Looking forward to doing the merge!

**Comment by BrettBailey** [comment]
@EricWhiteDev Looks like you've had a great big merge jamboree. I'm looking forward to using all the new features.  @chrlutz 's multiline stuff will be very useful

**Pull request merged**
