### PR TITLE
Remove dependency on MediaDataPartType, which doesn't contain MP4

### LINKED ISSUE #65: PresentationBuilder fails for PPTX that contain MP4
From a forum post:

Please take a look at the code I got from PresentationBuilder::CopyRelatedMedia and the definition of DocumentFormat.OpenXml.Packaging.MediaDataPartType.

Since MediaDataPartType doesn't have mp4 in its enumeration, PowerTools GetMediadataPartTypeFromContentType uses the default value - MediaDataPartType.Wmv - as mp4 media type. That is why mp4 file cannot be played correctly.

I can play my mp4 in my original pptx. I converted my mp4 to .avi file and inserted it in my original pptx. Both .mp4 and .avi can play. After copied version generated, only .avi file can play, but .mp4 gives the error "Codec Unavailable".

From Eric White: This needs an adjustment to GetMediadataPartTypeFromContentType.

```
        if (temp.DataPart == null)
        {
            var ct = oldPart.ContentType;
            <strong>MediaDataPartType </strong>mdpt = <strong>GetMediadataPartTypeFromContentType</strong>(ct);
            MediaDataPart newPart = newContentPart.OpenXmlPackage.CreateMediaDataPart(mdpt);
            newPart.FeedData(oldPart.GetStream());
```

private static MediaDataPartType GetMediadataPartTypeFromContentType(string ct)
        {
            MediaDataPartType mdpt = MediaDataPartType.Wmv;

```
        if (ct == "audio/aiff")
            mdpt = MediaDataPartType.Aiff;
        else if (ct == "video/x-ms-asf-plugin")
            mdpt = MediaDataPartType.Asx;
        else if (ct == "video/avi")
            mdpt = MediaDataPartType.Avi;
        else if (ct == "audio/midi")
            mdpt = MediaDataPartType.Midi;
        else if (ct == "audio/mp3")
            mdpt = MediaDataPartType.Mp3;
        else if (ct == "audio/mpeg")
            mdpt = MediaDataPartType.MpegAudio;
        else if (ct == "audio/mpegurl")
            mdpt = MediaDataPartType.MpegUrl;
        else if (ct == "video/mpeg")
            mdpt = MediaDataPartType.MpegVideo;
        else if (ct == "video/mpg")
            mdpt = MediaDataPartType.Mpg;
        else if (ct == "audio/ogg")
            mdpt = MediaDataPartType.OggAudio;
        else if (ct == "video/ogg")
            mdpt = MediaDataPartType.OggVideo;
        else if (ct == "video/quicktime")
            mdpt = MediaDataPartType.Quicktime;
        else if (ct == "video/vc1")
            mdpt = MediaDataPartType.VC1;
        else if (ct == "audio/wav")
            mdpt = MediaDataPartType.Wav;
        else if (ct == "audio/x-ms-wma")
            mdpt = MediaDataPartType.Wma;
        else if (ct == "video/x-ms-wmv")
            mdpt = MediaDataPartType.Wmv;
        else if (ct == "video/x-ms-wmx")
            mdpt = MediaDataPartType.Wmx;
        else if (ct == "video/x-ms-wvx")
            mdpt = MediaDataPartType.Wvx;
        else if (ct == "audio/unknown")
            mdpt = MediaDataPartType.Wav;
        return mdpt;
    }
```

namespace DocumentFormat.OpenXml.Packaging
{
    // Summary:
    //     Defines part media types.
    public enum MediaDataPartType
    {
        // Summary:
        //     Audio Interchange File Format (.aiff)
        Aiff = 0,
        //
        // Summary:
        //     MIDI Audio (.mid)
        Midi = 1,
        //
        // Summary:
        //     MP3 (.mp3)
        Mp3 = 2,
        //
        // Summary:
        //     MP3 Playlist File (.m3u)
        MpegUrl = 3,
        //
        // Summary:
        //     WAV audio (.wav)
        Wav = 4,
        //
        // Summary:
        //     Windows Media Audio File (.wma)
        Wma = 5,
        //
        // Summary:
        //     Mpeg audio (.mpeg)
        MpegAudio = 6,
        //
        // Summary:
        //     Ogg Vorbis (.ogg)
        OggAudio = 7,
        //
        // Summary:
        //     Advanced Stream Redirector File (.asx)
        Asx = 8,
        //
        // Summary:
        //     Audio Video Interleave File (.avi)
        Avi = 9,
        //
        // Summary:
        //     MPEG 1 System Stream (.mpg)
        Mpg = 10,
        //
        // Summary:
        //     MPEG 1 System Stream (.mpeg)
        MpegVideo = 11,
        //
        // Summary:
        //     Windows Media File (.wmv)
        Wmv = 12,
        //
        // Summary:
        //     Windows Media Player A/V Shortcut (.wmx)
        Wmx = 13,
        //
        // Summary:
        //     Windows Media Redirector (.wvx)
        Wvx = 14,
        //
        // Summary:
        //     QuickTime video (.mov)
        Quicktime = 15,
        //
        // Summary:
        //     Ogg Stream (.ogg)
        OggVideo = 16,
        //
        // Summary:
        //     VC-1 Stream (.wmv)
        VC1 = 17,
    }
}

### PR DESCRIPTION
**Pull request by kimsey0**
MediaDataPartType isn't really needed. It's only used to find the content type and file extension for a media file, and we already have those from the previous media part. Since MediaDataPartType doesn't contain a value for MP4, this Fixes #65.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by kimsey0** [comment]
@EricWhiteDev: Any chance this could be merged?

**Comment by kimsey0** [comment]
I have added a test case that `PresentationBuilder` preserves media content types. It shows the problem with MP4 videos and prevents any regressions.

**Comment by kimsey0** [comment]
I have added a test case that `PresentationBuilder` preserves media content types. It shows the problem with MP4 videos and prevents any regressions.  @EricWhiteDev

**Pull request merged**
