### PR TITLE
Use InvariantCulture when converting doubles to and from String

### PR DESCRIPTION
**Pull request by Zache**
When running the units tests on a machine with the Swedish culture set a number of them fail, this is also a problem when using the library. Here are two open issues caused by this: #52, #75. #38 is a closed issue that tried to address the problem, but missed  a couple of spots.

Here I have tried to fix the remaining issues, now all tests pass for me using either en-US or sv-SE as my culture.

### CODE REVIEW

**Comment by ThomasBarnekow** [comment]
@Zache, I've run into the exact same issue, so would like to see this getting merged.
@EricWhiteDev, please do have a look.

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev, this looks good to me.

@Zache, could you please rebase your branch on vNext so @EricWhiteDev can merge this (while keeping the history clean)?

**Comment by Zache** [comment]
@ThomasBarnekow @EricWhiteDev Done!

**Comment by ThomasBarnekow** [comment]
@Zache Thanks a lot!

@EricWhiteDev Please merge this before merging anything else.

**Comment by EricWhiteDev** [comment]
@Zache @ThomasBarnekow Merged, thank you!

**Pull request merged**
