### PR TITLE
Beautify and optimize

### PR DESCRIPTION
**Pull request by ThomasBarnekow**
This pull request beautifies and enhances OpenXmlRegex and the associated example as well as WordprocessingMLUtil. It beautifies MarkupSimplifier and the classes and methods contained in PtUtil.cs. 

It adds the XmlUtil class with two GetSpacePreserveAttribute methods (leaving a todo to use those methods in other classes that implement their own private methods for that purpose).

### CODE REVIEW

**Comment by ThomasBarnekow** [comment]
Hi @msftclas, I already signed a CLA a while ago to contribute to the Open XML SDK.

**Comment by ThomasBarnekow** [comment]
Hey @EricWhiteDev, this is what we talked about, so please do have a look. @richard-jr-lewis and @porkopek, this solves your issues with the w:tab and w:br elements while also dealing with (hopefully) all other run content (e.g., w:sym, w:noBreakHyphen, w:softHyphen) that should be mapped to Unicode values.

**Comment by ThomasBarnekow** [comment]
The last commit ("Fix and beautify AddNonBreakingSpacesForSpansWithWidth") has nothing to do with the changes made to other classes in this PR. The unit test had failed (see #101) before and I just fixed the error.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by ThomasBarnekow** [comment]
@tomjebo, I rebased onto vNext after your latest merge introduced a conflict.

**Comment by ThomasBarnekow** [comment]
With this latest commit, I upgraded the solution to the latest NuGet package (2.7.2-vnext0027).

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev, I rebased onto vNext again after your latest commits. Could you please review this PR and merge so I don't have to do that again?

This pull request contains bug fixes (e.g., for MarkupSimplifier) and relevant enhancements (e.g., of OpenXmlRegex). All unit tests pass.

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev, I forgot to mention that the commit entitled "Enhance PtOpenXmlExtensions" (5b58e58) is important for people working with both the strongly typed classes and the PowerTools. In the moment, the PowerTools don't work with the strongly typed classes or anything else that writes to the part streams while bypassing the `PutXDocument` methods, which is due to the caching done by `GetXDocument` and `PutXDocument`.

**Pull request merged**
