### PR TITLE
Update projects to use NuGet and new csproj format

### PR DESCRIPTION
**Pull request by twsouthwick**
As part of being able to support .NET Core, this change does the following:

- Update to the latest NuGet of DocumentFormat.OpenXml
- Convert projects to use the new csproj format (will allow .NET Standard targeting at a later point)
- Consolidates solution files into one file that has the tool, tests, and examples
- Removes the cmdlets (as suggested by @EricWhiteDev)

Initial support for #116

### CODE REVIEW

**Comment by twsouthwick** [comment]
@EricWhiteDev can you take a look at this? It gets the project ready to add .NET Standard support and cleans up the project system in general

**Comment by EricWhiteDev** [comment]
Sure, I'll take a look.

**Comment by EricWhiteDev** [comment]
@twsouthwick Could we have a phone call about this - these are pretty big changes, want to understand at a high level what you did, and why...

**Comment by twsouthwick** [comment]
Sure. I'll pm you and set up a call

**Comment by EricWhiteDev** [comment]
@twsouthwick Did you send a meeting request?

**Comment by twsouthwick** [comment]
Closing for now - @EricWhiteDev is going to make some changes that will affect this, and then I'll reopen a new PR against those changes.

**Comment by twsouthwick** [comment]
@EricWhiteDev I'm reopening this as this should still be done. It will simplify a ton of aspects of the project. Please let me know when you remove the cmdlets (I can take care of that with this as well, if you'd like)

**Comment by EricWhiteDev** [comment]
@twsouthwick I'll connect with you off-line, discuss.

**Comment by tikal** [comment]
Any update on this ?

**Comment by twsouthwick** [comment]
I talked with @EricWhiteDev a few months ago, and he was going to remove the cmdlets and then take this change. I haven't seen any action on that, though

**Comment by jacobbutton** [comment]
So whats the hold up on this?

**Comment by twsouthwick** [comment]
@EricWhiteDev can we get an ETA on when you'll remove the cmdlets so I can update this? I'm happy to do the work we discussed a few months back to help expedite this

**Comment by twsouthwick** [comment]
@EricWhiteDev I've updated this PR to include removing the cmdlets. Unless I hear otherwise, I'll go ahead and get this merged in by EOW

**Comment by EricWhiteDev** [comment]
@twsouthwick Sounds good

**Pull request merged**
